### ISSUE TITLE
Making better directory structure.

### ISSUE THREAD

**Issue by Preet-Sojitra** [csdojo-defaang/active-repos-for-contributing#14]
I think adding all the repo list directly in the README.md is not good idea because eventually it will become so long that it will be difficult to find particular repos (suppose I wanted repo for JS, so it will be difficult to find). 
Different directories can be made with languages name (like JS, TS, Go, etc) which will contains the list of all repos for  particular langauge only. Now this can be linked to main README file, so main README will be short and concise.

What are your take on this?

**Comment by ykdojo** [comment]
yes that sounds like a great idea!

**Comment by Preet-Sojitra** [comment]
I am ready to work on this

**Comment by ykdojo** [comment]
Thank you, that'll be great

**Comment by ykdojo** [comment]
@Preet-Sojitra still working on it?

**Comment by Preet-Sojitra** [comment]
Sorry, I am not working on this because I am little bit busy these days, so if anyone wants to work on this issue they can or if you want to assign it to anyone else then please do it because for 2 weeks I am busy so it won't be possible for me to do.

**Comment by Nakamcode** [comment]
I want to work on this !

**Comment by ykdojo** [comment]
Thank you so much @Nakamcode, I'll assign you then
