### ISSUE TITLE
Have a guideline on what repos should be here

### ISSUE THREAD

**Issue by ykdojo** [csdojo-defaang/active-repos-for-contributing#37]
Perhaps something like:

- The repo needs to be active (at least X commits over Y time)
- It needs to have either
    - Evidence that it's a solid project (e.g., # stars)
    - Evidence that it's a good repo for contributing (active PR history)

**Comment by ykdojo** [comment]
^add this as a new file

**Comment by Purva2803** [comment]
hey YK, I want to work on this documentation please assign me this issue.
