### ISSUE TITLE
Explain what this repo is for exactly

### ISSUE THREAD

**Issue by ykdojo** [csdojo-defaang/active-repos-for-contributing#39]
This repo exists to help people find open source repos to contribute to.

There are many, many repos on GitHub, and it's hard to know which ones are friendly and/or interesting to get involved with.

By keeping this list, it will hopefully make the process of finding a repo simpler.

**Comment by ykdojo** [comment]
^Add this to README

**Comment by suresh37** [comment]
assign me this task

**Comment by suresh37** [comment]
Please check my PR
